inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - "conformance/gen/**/*"

Style/StringLiterals:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/ClassMethodsDefinitions:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline
