# frozen_string_literal: true
# rbs_inline: enabled

# Copyright 2026 IVRy Inc.
# SPDX-License-Identifier: Apache-2.0

module ConnectRpcRails
  # Binds a protobuf ServiceDescriptor (generated by protoc/buf and present in the
  # descriptor pool) to a plain-Ruby handler object. Dispatch is reflection-based:
  # method routing and the input/output message classes come entirely from the
  # descriptor, so no per-service code generation is required.
  class ServiceRegistration
    Rpc = Struct.new(:name, :handler_method, :input_class, :output_class, keyword_init: true)

    attr_reader :service_name #: String
    attr_reader :handler #: untyped

    #: (untyped descriptor, untyped handler) -> void
    def initialize(descriptor, handler)
      @service_name = descriptor.name
      @handler = handler
      @rpcs = {} #: Hash[String, Rpc]

      descriptor.each do |method|
        ruby_method = ConnectRpcRails.underscore(method.name)
        unless handler.respond_to?(ruby_method)
          raise ArgumentError,
            "#{handler.class} must implement ##{ruby_method} for rpc " \
              "#{descriptor.name}/#{method.name}"
        end

        @rpcs[method.name] = Rpc.new(
          name: method.name,
          handler_method: ruby_method,
          input_class: method.input_type.msgclass,
          output_class: method.output_type.msgclass,
        )
      end
    end

    #: (String) -> Rpc?
    def rpc(name)
      @rpcs[name]
    end
  end
end
