# frozen_string_literal: true
# rbs_inline: enabled

# Copyright 2026 IVRy Inc.
# SPDX-License-Identifier: Apache-2.0

require "google/protobuf"

module ConnectRpcRails
  # Reads a protobuf ServiceDescriptor (generated by protoc/buf and present in the
  # descriptor pool) into the RPC table the transport dispatches from. Dispatch is
  # reflection-based: the action names and the input/output message classes come
  # entirely from the descriptor, so no per-service code generation is required.
  #
  # The service is named the way the `.proto` names it — `"greet.v1.GreetService"` — and
  # looked up in the pool, so the string in the code is greppable from the protobuf
  # definition. A ServiceDescriptor is accepted too, for a host that already holds one.
  #
  # The service is implemented by the controller itself — the RPC methods are ordinary
  # controller instance methods. There is deliberately no handler object: a handler held
  # on the controller class would be one instance shared by every request in the process,
  # so leftover instance state could leak between callers, whereas Rails builds a
  # controller per request.
  class ServiceRegistration
    Rpc = Struct.new(:name, :action, :input_class, :output_class, keyword_init: true)

    attr_reader :service_name #: String

    #: (String | untyped service) -> void
    def initialize(service)
      descriptor = service.is_a?(String) ? self.class.lookup!(service) : service
      @service_name = descriptor.name
      @rpcs = {} #: Hash[String, Rpc]

      descriptor.each do |method|
        action = ConnectRpcRails.underscore(method.name)
        @rpcs[action] = Rpc.new(
          name: method.name,
          action: action,
          input_class: method.input_type.msgclass,
          output_class: method.output_type.msgclass,
        )
      end
    end

    # The generated `_pb` file has to have been required, since requiring it is what puts
    # the service in the pool. Say so, rather than let a typo and a missing require look
    # the same.
    #: (String) -> untyped
    def self.lookup!(service_name)
      Google::Protobuf::DescriptorPool.generated_pool.lookup(service_name) ||
        raise(ArgumentError, "no service #{service_name} in the descriptor pool: is its generated _pb file required?")
    end

    #: () -> Array[Rpc]
    def rpcs
      @rpcs.values
    end
  end
end
